#!/bin/bash

SSH_KEY_PATH="$HOME/.ssh/id_ed25519"

# Cores
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
NC="\033[0m"

# Emojis
INFO="ℹ️ "
CHECK="✅"
ERROR="❌"

print_logs=()

add_message() {
  if [ "$2" = true ]; then
    clear
  fi

  print_logs[${#print_logs[@]}]=$1
}

print_messages() {
  for element in "${print_logs[@]}"; do
    echo "$element"
  done
}

# Funções
select_ssh_key() {
  echo -e "\n${INFO}Select SSH key:"
  options=("github @lamecksilva (~/.ssh/id_ed25519)" "github @lamecksilvacasar (~/.ssh/id_rsa_casar)" "Cancel")
  select opt in "${options[@]}"; do
    case $REPLY in
    1)
      SSH_KEY_PATH="$HOME/.ssh/id_ed25519"
      break
      ;;
    2)
      SSH_KEY_PATH="$HOME/.ssh/id_rsa_casar"
      break
      ;;
    3)
      echo -e "${INFO}Canceled."
      return
      ;;
    *)
      echo -e "${ERROR}Invalid option."
      continue
      ;;
    esac
  done

  add_message "${CHECK} SSH key selected: $SSH_KEY_PATH" true
}

show_selected_key() {
  add_message "\n${INFO}Current SSH key: ${YELLOW}${SSH_KEY_PATH}${NC}" true
}

git_add() {
  add_message "${INFO}Adding files..."
  git add .
  add_message "${CHECK} Files added."
}

git_commit() {
  read -p "${INFO}Write commit message: " commit_msg
  git commit -m "$commit_msg" && echo -e "${CHECK} Commit done."
}

git_fetch() {
  add_message "${INFO}Fetching with key: $SSH_KEY_PATH"
  GIT_SSH_COMMAND="ssh -i $SSH_KEY_PATH -o IdentitiesOnly=yes" git fetch
}

git_push() {
  add_message "${INFO}Pushing with key: $SSH_KEY_PATH"
  GIT_SSH_COMMAND="ssh -i $SSH_KEY_PATH -o IdentitiesOnly=yes" git push
}

git_pull() {
  add_message "${INFO}Pulling with key: $SSH_KEY_PATH"
  GIT_SSH_COMMAND="ssh -i $SSH_KEY_PATH -o IdentitiesOnly=yes" git pull
}

while true; do
  print_messages

  echo -e "\n${YELLOW}=============================${NC}"
  echo -e "${GREEN}  Git Helper Menu${NC}"
  echo -e "${YELLOW}=============================${NC}"
  echo " [a]   git add ."
  echo " [c]   git commit -m"
  echo " [f]   git fetch"
  echo " [p]   git push"
  echo " [pl]  git pull"
  echo " [acp] add + commit + push"
  echo " [k]   Select SSH key"
  echo " [s]   Show selected SSH key"
  echo " [q]   Quit"
  echo ""

  read -p "Select option: " opt

  case $opt in
  "a") git_add ;;
  "c") git_commit ;;
  "f") git_fetch ;;
  "p") git_push ;;
  "pl") git_pull ;;
  "acp")
    git_add
    git_commit
    git_push
    ;;
  "k") select_ssh_key ;;
  "s") show_selected_key ;;
  "q" | "")
    echo -e "${INFO}Goodbye!"
    break
    ;;
  *) echo -e "${ERROR}Invalid option!" ;;
  esac
done
